


resources:
# The repo with our Dockerfile
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/juan-bolivar/onboarding-tasks.git
    branch: infra

jobs:
- name: build-and-run
  plan:
  - get: concourse-examples
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: concourse-examples
      outputs:
      - name: image
      params:
        CONTEXT: concourse-examples
        UNPACK_ROOTFS: true #add this param
      run: # binary used to build the image
        path: build

  - task: packer  # add a new task step
    image: image  # using the image built in the previous step
    config:
      platform: linux
      run:
        path: sh
        args:
          - -exc
          - mkdir /usr/src/app/output && cd /usr/src/app/packer && packer build -machine-readable . | tee /usr/src/app/output/build.log
      params:
        AWS_ACCESS_KEY_ID: ((AWS_KEY))
        AWS_SECRET_ACCESS_KEY: ((AWS_SECRET))
        AWS_REGION: ((AWS_REGION))
        AWS_DEFAULT_REGION: ((AWS_DEFAULT_REGION))

      outputs:
      - name: image_packer
 
  - task: ls  # add a new task step
    image: image_packer  # using the image built in the previous step
    config:
      platform: linux
      run:
        path: sh
        args:
          - -exc
          - ls /usr/src/app/output 
 
