resources:
# The repo with our Dockerfile
- name: concourse-examples
  type: git
  icon: github
  source:
    uri: https://github.com/juan-bolivar/onboarding-tasks.git
    branch: infra

jobs:
- name: build-and-run
  plan:
  - get: concourse-examples
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: concourse-examples
      outputs:
      - name: image
      params:
        CONTEXT: concourse-examples
        UNPACK_ROOTFS: true #add this param
      run: # binary used to build the image
        path: build

  - task: packer  # add a new task step
    image: image  # using the image built in the previous step
    privileged: true # oci-build-task must run in a privileged container
    config:
      inputs:
      - name: concourse-examples
      outputs:
      - name: output_packer
      platform: linux
      run:
        path: sh
        args:
        - -exc
        - |
          cd concourse-examples/packer && packer build -machine-readable . | tee ../../output_packer/build.log
          cd ..
          cd ..
          grep "artifact,0,id" output_packer/build.log  | tee output_packer/ami.out
          cut -d "," -f6 output_packer/ami.out  | tee output_packer/temp.out
          cut -d ":" -f2 output_packer/temp.out | tee output_packer/ami-id.out
      params:
        AWS_ACCESS_KEY_ID: ((AWS_KEY))
        AWS_SECRET_ACCESS_KEY: ((AWS_SECRET))
        AWS_REGION: ((AWS_REGION))
        AWS_DEFAULT_REGION: ((AWS_DEFAULT_REGION))
 
  - task: terraform  # add a new task step
    image: image
    privileged: true
    config:
      inputs:
      - name: output_packer
      - name: concourse-examples
      platform: linux
      run:
        path: sh
        args:
        - -exc
        - |
          ls 
          ami_id=$(cat output_packer/ami-id.out)
          cd concourse-examples/terraform && terraform init  && terraform apply -var="ami_id=$ami_id" -var="region=((AWS_REGION))" -auto-approve
      params:
        AWS_ACCESS_KEY_ID: ((AWS_KEY))
        AWS_SECRET_ACCESS_KEY: ((AWS_SECRET))
        AWS_REGION: ((AWS_REGION))
        AWS_DEFAULT_REGION: ((AWS_DEFAULT_REGION))

  - task: kubernetes  # add a new task step
    image: image
    privileged: true
    config:
      inputs:
      - name: output_packer
      - name: concourse-examples
      platform: linux
      run:
        path: sh
        args:
        - -exc
        - |
          ls
          cd concourse-examples/kubernetes
          bash script.sh 
      params:
        AWS_ACCESS_KEY_ID: ((AWS_KEY))
        AWS_SECRET_ACCESS_KEY: ((AWS_SECRET))
        AWS_REGION: ((AWS_REGION))
        AWS_DEFAULT_REGION: ((AWS_DEFAULT_REGION))
 





 
